#!/usr/bin/env node
// server/index.js — minimal static server for local dev.
//
// In production, nginx in the Docker image (docker/nginx.conf) serves
// dist/ — this file is for `npm start` during development only.
//
// Routes:
//   /             → /edit.html
//   /<anything>   → dist/<anything>
//   404 for missing files (NO SPA fallback — editor expects real 404s)
//
// Headers: COOP/COEP set on every response (matches nginx.conf).
//
// No deps beyond Node stdlib. Listens on env PORT or 8080.

"use strict";

const fs = require("node:fs");
const http = require("node:http");
const path = require("node:path");
const url = require("node:url");

const PORT = parseInt(process.env.PORT || "8080", 10);
const DIST = path.join(__dirname, "..", "public");

if (!fs.existsSync(DIST)) {
  console.error(
    "ERROR: dist/ does not exist. Run `bash build/build.sh` first.",
  );
  process.exit(1);
}

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".wasm": "application/wasm",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
};

function send404(res, requested) {
  res.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
  res.end("Not found: " + requested);
}

// The big, rarely-changing vendor trees — only regenerated by a full build
// (`npm run initialize`). The editor bundle alone is ~20 MB, so we cache these
// hard and never want them re-fetched on a reload.
function isVendorAsset(p) {
  return /^\/(sdkjs|web-apps|fonts|x2t)\//.test(p);
}

function cacheControlFor(p) {
  // Vendor assets (but not their .html shells): immutable, long cache.
  if (isVendorAsset(p) && /\.(js|wasm|woff2?|ttf|png|jpe?g|svg|gif|ico|css)$/.test(p)) {
    return "public, max-age=31536000, immutable";
  }
  // Everything else — our editable wrapper glue (`/wrapper-*.js`,
  // `/editor-stubs.js`, `/x2t-bridge.js`, `/edit.css`, `/icons/*`) and all HTML —
  // must REVALIDATE so a plain reload picks up `npm run sync` edits (no
  // hard-reload needed). Combined with Last-Modified + 304 below, unchanged
  // files still return cheaply.
  return "no-cache";
}

function serveFile(res, req, abs, requested) {
  fs.stat(abs, (err, st) => {
    if (err || !st.isFile()) return send404(res, requested);

    // Conditional GET: let `no-cache` revalidate to a cheap 304 instead of
    // re-sending the body when the file hasn't changed since the last fetch.
    const lastModified = st.mtime.toUTCString();
    const ims = req.headers["if-modified-since"];
    if (ims && Date.parse(ims) >= Math.floor(st.mtimeMs / 1000) * 1000) {
      res.writeHead(304, {
        "Cache-Control": cacheControlFor(requested),
        "Last-Modified": lastModified,
      });
      return res.end();
    }

    const ext = path.extname(abs).toLowerCase();
    res.writeHead(200, {
      "Content-Type": MIME[ext] || "application/octet-stream",
      "Cache-Control": cacheControlFor(requested),
      "Last-Modified": lastModified,

      // NOTE on COOP/COEP — DO NOT enable Cross-Origin-Opener-Policy
      // here. Setting it to 'same-origin' severs window.opener for
      // cross-origin popups (which is exactly our deployment shape).
      // Without window.opener, the editor cannot postMessage back to
      // the main app, and connection-lost polling false-fires.
      //
      // The HarfBuzz + x2t WASM modules our editor uses are
      // single-threaded — they don't need SharedArrayBuffer (which is
      // what COOP same-origin would unlock). Plain ArrayBuffer is
      // sufficient.
      //
      // If you ever introduce multi-threaded WASM that DOES need
      // SharedArrayBuffer, switch to embedding the editor as an iframe
      // (where COOP doesn't break parent/child postMessage) instead
      // of a popup.

      // Permissive CORS — if app.hostname.com fetches assets directly.
      "Access-Control-Allow-Origin": "*",

      // Discourage indexing.
      "X-Robots-Tag": "noindex, nofollow",
    });
    fs.createReadStream(abs).pipe(res);
  });
}

http
  .createServer((req, res) => {
    const u = url.parse(req.url);
    let p = decodeURIComponent(u.pathname || "/");

    if (p === "/") p = "/edit.html";

    // Path traversal guard.
    const safe = path.normalize(p).replace(/^(\.\.[\/\\])+/, "");
    const abs = path.join(DIST, safe);
    if (!abs.startsWith(DIST)) return send404(res, p);

    serveFile(res, req, abs, p);
  })
  .listen(PORT, () => {
    console.log("[sharekey-office] dev server on http://localhost:" + PORT);
    console.log("[sharekey-office] serving:", DIST);
    console.log(
      "[sharekey-office] open via your main app's window.open(...) flow",
    );
  });
