#!/usr/bin/env bash
# Post-build hook: inject <script src="/wrapper-boot.js"></script> into the
# deployed editor index.html so our license shim runs before require(['app']).
#
# The deployed index.html is a build artifact (regenerated by `grunt
# deploy-app-main`), so this script must be run AFTER each build. Idempotent
# — running twice does not double-inject.
#
# Usage:
#   inject-boot.sh [--web-apps PATH] [--editors LIST]
#
# Exit codes: 0 ok, 1 missing prereqs.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

WEB_APPS=""
# SCRIPT_DIR is .../sharekey-office/wrapper/v1/web-apps-overlay.
# The build passes --web-apps explicitly (build/03-deploy-web-apps.sh), so the
# auto-detect below is only a dev fallback: walk up for a `web-apps/deploy`,
# preferring sharekey-office/vendor/web-apps.
for candidate in \
  "$SCRIPT_DIR/../../../vendor/web-apps" \
  "$SCRIPT_DIR/../../../../web-apps" \
; do
  if [[ -d "$candidate/deploy" ]]; then
    WEB_APPS="$( cd "$candidate" && pwd )"
    break
  fi
done

EDITORS="documenteditor"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --web-apps) WEB_APPS="$2"; shift 2 ;;
    --editors)  EDITORS="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$WEB_APPS" || ! -d "$WEB_APPS/deploy" ]]; then
  echo "ERROR: web-apps deploy not found. Run 'npx grunt deploy-documenteditor' first." >&2
  exit 1
fi

MARKER="<!-- wrapper-boot-injected -->"
# Order matters: editor-stubs.js patches CDocsCoApi.prototype etc. AS SOON AS
# the SDK bundle defines them, so it must run before requirejs starts loading
# the editor's app.js. wrapper-boot.js comes after for license shim + SDK
# loader hints.
INJECTED="    $MARKER
    <script src=\"/editor-stubs.js\"></script>
    <script src=\"/wrapper-boot.js\"></script>
"
# We inject just before the existing requirejs <script> tag so our shim runs
# *before* require.js loads app.js.
ANCHOR='<script src="../../../vendor/requirejs/require.js"></script>'

IFS=',' read -r -a EDITOR_ARR <<< "$EDITORS"
for editor in "${EDITOR_ARR[@]}"; do
  html="$WEB_APPS/deploy/web-apps/apps/${editor}/main/index.html"
  if [[ ! -f "$html" ]]; then
    echo "  skip $editor (no $html)"; continue
  fi

  if grep -qF "$MARKER" "$html"; then
    echo "  $editor already injected (skip)"
    continue
  fi
  if ! grep -qF "$ANCHOR" "$html"; then
    echo "ERROR: anchor not found in $html — the build's index.html shape changed?" >&2
    exit 1
  fi

  # Node helper — avoids relying on a system Python interpreter.
  node "$SCRIPT_DIR/inject-into-html.js" "$html" "$ANCHOR" "$INJECTED"
  echo "  injected $editor"
done

echo
echo "Done."
